export type BazarKey =
  | 'SRIDEVI_OPEN'
  | 'SRIDEVI_CLOSED'
  | 'TIME_OPEN'
  | 'TIME_CLOSED'
  | 'DIVAS_MILAN_OPEN'
  | 'DIVAS_MILAN_CLOSED'
  | 'KALYAN_OPEN'
  | 'KALYAN_CLOSED'
  | 'NIGHT_MILAN_OPEN'
  | 'NIGHT_MILAN_CLOSED'
  | 'MAIN_BAZAR'
  | 'MAIN_BAZAR_CLOSED'
  | 'CM_1'
  | 'CM_2'
  | 'CM_3'
  | 'CM_4'
  | 'CM_5'
  | 'CM_6'
  | 'CM_7'
  | 'CM_8'
  | 'CM_9'
  | 'CM_10'
  | 'CM_11'
  | 'CM_12'

export type BulkBetType =
  | 'SP'
  | 'DP'
  | 'JODI'
  | 'DADAR'
  | 'EKI'
  | 'BEKI'
  | 'ABR_CUT'
  | 'JODI_PANEL'
  | 'MOTAR'
  | 'COMMAN_PANA_36'
  | 'COMMAN_PANA_56'
  | 'SET_PANA'
  | 'GROUP'

export type BetType = BulkBetType | 'SINGLE' | 'COLUMN'
